-- Question 1
SELECT ANNEE, NUMERO_TICKET as 'N°' FROM vendre WHERE ID_ARTICLE = 500;
-- Question 2
SELECT `ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE `DATE_VENTE` = '2017-01-15 23:00:00';
-- Question 3
SELECT `ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE `DATE_VENTE` BETWEEN '2017-01-15 23:00:00' AND '2017-01-17 23:00:00';
SELECT `ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE `DATE_VENTE` in ('2017-01-15 23:00:00','2017-01-16 23:00:00','2017-01-17 23:00:00');
-- Question 4
SELECT DISTINCT A.`ID_ARTICLE`, A.`NOM_ARTICLE` FROM `article` AS A INNER JOIN `vendre` as V ON V.ID_ARTICLE = A.ID_ARTICLE WHERE V.QUANTITE >= 95;
SELECT A.`ID_ARTICLE`, A.`NOM_ARTICLE` FROM `article` AS A INNER JOIN `vendre` AS V ON V.ID_ARTICLE = A.ID_ARTICLE WHERE V.QUANTITE >= 95 GROUP BY A.ID_ARTICLE, A.NOM_ARTICLE;
SELECT DISTINCT V.`ID_ARTICLE` AS CODE, (SELECT A.NOM_ARTICLE FROM `article` AS A WHERE A.ID_ARTICLE = V.ID_ARTICLE ) AS NOM FROM `vendre` AS V WHERE V.QUANTITE >=95;
-- Question 5
SELECT`ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE `DATE_VENTE` BETWEEN '2017-03-01 23:00:00' AND '2017-03-31 23:00:00';
SELECT`ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE YEAR(`DATE_VENTE`) = 2017 AND MONTH(`DATE_VENTE`) = 3;
SELECT`ANNEE`,`NUMERO_TICKET`,`DATE_VENTE` FROM `ticket` WHERE `ANNEE` = 2017 AND MONTH(`DATE_VENTE`) = 3;
-- Question 6
SELECT * FROM `ticket` WHERE `DATE_VENTE`BETWEEN '2017-04-01 23:00:00' AND '2017-06-30 23:00:00';
SELECT * FROM `ticket` WHERE `ANNEE` = 2017 AND MONTH(`DATE_VENTE`) in (4,5,6);
SELECT * FROM `ticket` WHERE `ANNEE` = 2017 AND MONTH(`DATE_VENTE`) BETWEEN 4 AND 6;
-- Question 7
SELECT * FROM `ticket` WHERE `ANNEE` = 2017 AND MONTH(`DATE_VENTE`) in (3,7);
-- Question 8
SELECT A.`ID_ARTICLE` as Code, A.`NOM_ARTICLE`as libelle, C.NOM_COULEUR FROM `article` as A LEFT JOIN `couleur` as C ON A.ID_COULEUR = C.ID_COULEUR ORDER BY C.NOM_COULEUR;
SELECT A.`ID_ARTICLE` as Code, A.`NOM_ARTICLE`as libelle, C.NOM_COULEUR FROM `couleur` as C RIGHT JOIN `article` as A ON A.ID_COULEUR = C.ID_COULEUR ORDER BY C.NOM_COULEUR;
SELECT A.`ID_ARTICLE` as Code, A.`NOM_ARTICLE`as libelle, (SELECT C.NOM_COULEUR FROM couleur as C WHERE C.ID_COULEUR = A.ID_COULEUR) as Couleur FROM article as A ORDER BY Couleur;
-- Question 9
SELECT `ID_ARTICLE`,`NOM_ARTICLE` FROM `article` WHERE `ID_COULEUR` is null;
-- Question 10
SELECT A.`ID_ARTICLE` AS CODE, A.`NOM_ARTICLE` AS libelle, C.NOM_COULEUR, T.NOM_TYPE FROM `article` AS A INNER JOIN couleur AS C ON C.ID_COULEUR = A.ID_COULEUR JOIN typebiere AS T ON T.ID_TYPE = A.ID_TYPE WHERE A.`ID_ARTICLE` = 142;
SELECT A.`ID_ARTICLE` AS CODE, A.`NOM_ARTICLE` AS libelle, C.NOM_COULEUR, T.NOM_TYPE FROM `article` AS A INNER JOIN couleur AS C ON C.ID_COULEUR = A.ID_COULEUR INNER JOIN typebiere AS T ON T.ID_TYPE = A.ID_TYPE WHERE A.`ID_COULEUR` = (SELECT `ID_COULEUR` FROM `article` WHERE ID_ARTICLE = 142);
SELECT A.`ID_ARTICLE` AS CODE, A.`NOM_ARTICLE` AS libelle, C.NOM_COULEUR, T.NOM_TYPE FROM `article` AS A INNER JOIN couleur AS C ON C.ID_COULEUR = A.ID_COULEUR INNER JOIN typebiere AS T ON T.ID_TYPE = A.ID_TYPE WHERE A.`ID_COULEUR` = (SELECT `ID_COULEUR` FROM `article` WHERE ID_ARTICLE = 142) AND A.ID_TYPE = (SELECT `ID_TYPE` FROM `article` WHERE ID_ARTICLE = 142);
-- Question 11
SELECT `ANNEE`,`NUMERO_TICKET`,SUM(`QUANTITE`) as Quantité FROM `vendre` GROUP BY `ANNEE`,`NUMERO_TICKET` ORDER BY SUM(`QUANTITE`) DESC;
SELECT `ANNEE`,`NUMERO_TICKET`,SUM(`QUANTITE`) as Quantité FROM `vendre` GROUP BY `ANNEE`,`NUMERO_TICKET` ORDER BY Quantité DESC;
-- Question 12
SELECT `ANNEE`,`NUMERO_TICKET`,SUM(`QUANTITE`) as Quantité FROM `vendre` GROUP BY `ANNEE`,`NUMERO_TICKET` HAVING SUM(`QUANTITE`) < 50 ORDER BY Quantité ASC;
WITH LISTE(ANNEE, NUMERO_TICKET, QUANTITE)
as 
(SELECT ANNEE,NUMERO_TICKET, SUM(QUANTITE) as QUANTITE FROM vendre GROUP BY ANNEE,NUMERO_TICKET)
SELECT * FROM LISTE WHERE QUANTITE < 50 ORDER BY QUANTITE;
SELECT ANNEE,NUMERO_TICKET,
(SELECT SUM(QUANTITE) FROM vendre WHERE ANNEE = T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET) as Qté FROM ticket as T 
WHERE
(SELECT SUM(QUANTITE) FROM vendre WHERE ANNEE=T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET) < 50 ORDER BY Qté;
-- Question 13
SELECT ANNEE,NUMERO_TICKET, SUM(QUANTITE) as Quantité FROM vendre GROUP BY ANNEE,NUMERO_TICKET HAVING SUM(QUANTITE) > 500 ORDER BY Quantité DESC;
WITH LISTE(ANNEE,NUMERO_TICKET,QUANTITE)
as (SELECT ANNEE, NUMERO_TICKET, SUM(QUANTITE) as Quantité FROM vendre GROUP BY ANNEE, NUMERO_TICKET)
SELECT * FROM LISTE WHERE QUANTITE > 500 ORDER BY QUANTITE DESC;
SELECT ANNEE, NUMERO_TICKET,
(SELECT sum(QUANTITE) FROM vendre WHERE = T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET) as Qté
FROM ticket as T
WHERE
(SELECT SUM(QUANTITE) FROM vendre WHERE = T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET) > 500
ORDER BY Qté DESC;
-- Question 14
SELECT ANNEE,NUMERO_TICKET, SUM(QUANTITE) as Quantité FROM vendre WHERE QUANTITE <= 50 GROUP BY ANNEE,NUMERO_TICKET HAVING SUM(QUANTITE) > 500 ORDER BY Quantité DESC;
WITH LISTE(ANNEE,NUMERO_TICKET,QUANTITE)
as (SELECT ANNEE, NUMERO_TICKET, SUM(QUANTITE) as Quantité FROM vendre WHERE QUANTITE <= 50 GROUP BY ANNEE, NUMERO_TICKET)
SELECT * FROM LISTE WHERE QUANTITE > 500 ORDER BY QUANTITE DESC;
SELECT ANNEE, NUMERO_TICKET,
(SELECT sum(QUANTITE) FROM vendre WHERE = T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET AND QUANTITE <= 50) as Qté
FROM ticket as T
WHERE
(SELECT SUM(QUANTITE) FROM vendre WHERE = T.ANNEE AND NUMERO_TICKET = T.NUMERO_TICKET) > 500
ORDER BY Qté DESC;
-- Question 15
-- Lister les bières de type ‘Trappiste'. (id, nom de la bière, volume et titrage)
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME,TITRAGE FROM article JOIN typebiere as T ON T.ID_TYPE = article.ID_TYPE WHERE NOM_TYPE = 'Trappiste';
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME,TITRAGE FROM article WHERE ID_TYPE = (SELECT ID_TYPE FROM typebiere WHERE NOM_TYPE = 'Trappiste');
-- Question 16
SELECT ID_MARQUE,NOM_MARQUE,NOM_CONTINENT FROM Marque as M JOIN Pays as P ON P.ID_PAYS = M.ID_PAYS JOIN Continent as C ON C.ID_CONTINENT = P.ID_CONTINENT WHERE NOM_CONTINENT = 'Afrique';
SELECT ID_MARQUE,NOM_MARQUE FROM Marque as M JOIN Pays as P ON P.ID_PAYS = M.ID_PAYS WHERE P.ID_CONTINENT = (SELECT ID_CONTINENT FROM Continent WHERE NOM_CONTINENT = 'Afrique');
SELECT ID_MARQUE,NOM_MARQUE FROM Marque as M WHERE ID_PAYS in (SELECT ID_PAYS FROM Pays WHERE ID_CONTINENT = (SELECT ID_CONTINENT FROM Continent WHERE NOM_CONTINENT = 'Afrique'));
-- Question 17
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME FROM article as A 
JOIN Marque as M ON A.ID_MARQUE = M.ID_MARQUE
JOIN Pays as P ON P.ID_PAYS = M.ID_PAYS
JOIN Continent as C ON C.ID_CONTINENT = P.ID_CONTINENT
WHERE NOM_CONTINENT = 'Afrique';
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME FROM article as A 
JOIN Marque as M ON A.ID_MARQUE = M.ID_MARQUE
JOIN Pays as P ON P.ID_PAYS = M.ID_PAYS
WHERE P.ID_CONTINENT = (SELECT ID_CONTINENT FROM Continent WHERE NOM_CONTINENT = 'Afrique');
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME FROM article as A 
JOIN Marque as M ON A.ID_MARQUE = M.ID_MARQUE
WHERE ID_PAYS in
(SELECT ID_PAYS FROM Pays WHERE ID_CONTINENT =
(SELECT ID_CONTINENT FROM Continent WHERE NOM_CONTINENT = 'Afrique')
);
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME FROM article
WHERE ID_MARQUE in
(SELECT ID_MARQUE FROM Marque WHERE ID_PAYS in
(SELECT ID_PAYS FROM Pays WHERE ID_CONTINENT =
(SELECT ID_CONTINENT FROM Continent WHERE NOM_CONTINENT = 'Afrique')
)
);
-- Question 18
SELECT Année = ANNEE, Ticket = NUMERO_TICKET, 'A payer' = ROUND(SUM(QUANTITE * PRIX_VENTE * 1.20),2) FROM vendre as V GROUP BY ANNEE,NUMERO_TICKET ORDER BY 'A Payer' DESC;
-- Question 19
SELECT `ANNEE`, SUM(`QUANTITE`*`PRIX_VENTE`) as 'CA' FROM `vendre` GROUP BY `ANNEE` ORDER BY `ANNEE`;
-- Question 20
SELECT V.ID_ARTICLE, NOM_ARTICLE, SUM(QUANTITE) as 'Qté 2017' FROM vendre as V 
JOIN article as A ON A.ID_ARTICLE = V.ID_ARTICLE WHERE ANNEE = 2017 GROUP BY V.ID_ARTICLE, NOM_ARTICLE;
SELECT ID_ARTICLE, NOM_ARTICLE, (SELECT SUM(`QUANTITE`*`PRIX_VENTE`) FROM vendre WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2017) as 'Qté 2017'
FROM article as A;
SELECT V.ID_ARTICLE, NOM_ARTICLE, SUM(CASE WHEN ANNEE = 2017 THEN QUANTITE END) as 'Qté 2017' FROM vendre as V 
JOIN article as A ON A.ID_ARTICLE = V.ID_ARTICLE GROUP BY V.ID_ARTICLE, NOM_ARTICLE;
-- Question 21
SELECT ID_ARTICLE,NOM_ARTICLE,
(SELECT SUM(QUANTITE) FROM vendre WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014) as 'Qté 2014',
(SELECT SUM(QUANTITE) FROM vendre WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015) as 'Qté 2015',
(SELECT SUM(QUANTITE) FROM vendre WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2016) as 'Qté 2016',
(SELECT SUM(QUANTITE) FROM vendre WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2017) as 'Qté 2017'
FROM article as A;
SELECT ID_ARTICLE,NOM_ARTICLE,
SUM(CASE WHEN ANNEE = 2014 THEN QUANTITE END) as 'Qté 2014',
SUM(CASE WHEN ANNEE = 2015 THEN QUANTITE END) as 'Qté 2015',
SUM(CASE WHEN ANNEE = 2016 THEN QUANTITE END) as 'Qté 2016',
SUM(CASE WHEN ANNEE = 2017 THEN QUANTITE END) as 'Qté 2017'
FROM vendre as V
JOIN article as A ON A.ID_ARTICLE = V.ID_ARTICLE
GROUP BY A.ID_ARTICLE,NOM_ARTICLE;
-- Question 22
SELECT DISTINCT ANNEE, NUMERO_TICKET FROM vendre
WHERE ID_ARTICLE in (SELECT ID_ARTICLE FROM vendre WHERE ANNEE = 2017 AND NUMERO_TICKET = 5133);
SELECT ANNEE, NUMERO_TICKET FROM vendre
WHERE ID_ARTICLE in (SELECT ID_ARTICLE FROM vendre WHERE ANNEE = 2017 AND NUMERO_TICKET = 5133)
GROUP BY ANNEE, NUMERO_TICKET;
SELECT DISTINCT V1.ANNEE, V1.NUMERO_TICKET FROM vendre as V1
JOIN vendre as V2 ON V1.ID_ARTICLE = V2.ID_ARTICLE
WHERE V2.ANNEE = 2017 AND V2.NUMERO_TICKET = 5133;
SELECT V1.ANNEE, V1.NUMERO_TICKET FROM vendre as V1
JOIN vendre as V2 ON V1.ID_ARTICLE = V2.ID_ARTICLE
WHERE V2.ANNEE = 2017 AND V2.NUMERO_TICKET = 5133
GROUP BY V1.ANNEE,V1.NUMERO_TICKET;
-- Question 23
SELECT (SELECT NOM_TYPE FROM typebiere WHERE ID_TYPE = A.ID_TYPE) as Type,
ID_ARTICLE,
NOM_ARTICLE,
(SELECT SUM(QUANTITE) FROM vendre WHERE ANNEE = 2017 AND id_article = A.ID_ARTICLE) as Quantite
FROM article as A
WHERE (SELECT SUM(QUANTITE) FROM vendre WHERE ANNEE = 2017 AND ID_ARTICLE = A.ID_ARTICLE) = 
(SELECT DISTINCT MAX(SUM(QUANTITE)) OVER()
FROM vendre as V
WHERE ANNEE = 2017
AND (SELECT ID_TYPE FROM article WHERE ID_ARTICLE = V.ID_ARTICLE) = A.ID_TYPE
GROUP BY ID_ARTICLE
)
ORDER BY Quantite DESC;
SELECT NOM_TYPE as Type, A.ID_ARTICLE, NOM_ARTICLE, SUM(QUANTITE) as Quantite
FROM vendre as V
JOIN article as A ON A.ID_ARTICLE = V.ID_ARTICLE
JOIN typebiere as T ON T.ID_TYPE = A.ID_TYPE
WHERE ANNEE = 2017
GROUP BY A.ID_TYPE, NOM_TYPE, A.ID_ARTICLE, NOM_ARTICLE
HAVING SUM(QUANTITE)
= (SELECT DISTINCT MAX(SUM(QUANTITE)) OVER()
FROM vendre as V
WHERE ANNEE = 2017
AND (SELECT ID_TYPE
FROM article
WHERE ID_ARTICLE = V.ID_ARTICLE) = A.ID_TYPE
GROUP BY ID_ARTICLE)
ORDER BY Quantite DESC;
WITH Temp as (SELECT ID_TYPE, A.ID_ARTICLE, NOM_ARTICLE, SUM(QUANTITE) as Quantite
FROM vendre as V
JOIN article as A ON A.id_article = V.ID_ARTICLE
WHERE ANNEE = 2017
GROUP BY ID_TYPE, A.ID_ARTICLE, NOM_ARTICLE )
SELECT NOM_TYPE as Type, temp.ID_ARTICLE, NOM_ARTICLE, Quantite FROM temp
JOIN typebiere ON typebiere.ID_TYPE = temp.ID_TYPE
WHERE Quantite = (SELECT MAX(Quantite)
FROM temp as temp2
WHERE temp2.ID_TYPE = temp.ID_TYPE)
ORDER BY Quantite DESC;
-- Question 24
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014)
AND NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015);
SELECT ID_ARTICLE,NOM_ARTICLE,VOLUME FROM article as A
WHERE NOT EXISTS (SELECT * 
FROM vendre 
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE in (2014,2015));
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014)
INTERSECT
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015)
-- Question 25
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014)
AND EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015)
ORDER BY ID_ARTICLE;
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014)
INTERSECT
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015)
ORDER BY ID_ARTICLE;
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2014)
EXCEPT
SELECT ID_ARTICLE, NOM_ARTICLE, VOLUME FROM article as A
WHERE NOT EXISTS (SELECT *
FROM vendre
WHERE ID_ARTICLE = A.ID_ARTICLE AND ANNEE = 2015)
ORDER BY ID_ARTICLE;



-- Exercice Vue
SELECT DISTINCT `NOM_COULEUR` AS Couleur FROM `couleur` AS C INNER JOIN `article` AS A ON A.ID_COULEUR = C.ID_COULEUR;
SELECT C.NOM_COULEUR AS Couleur, SUM(V.`QUANTITE`*V.`PRIX_VENTE`) as 'CA 2014' FROM `vendre` AS V INNER JOIN `article` AS A ON A.ID_ARTICLE = V.ID_ARTICLE INNER JOIN `couleur` AS C ON C.ID_COULEUR = A.ID_COULEUR WHERE `ANNEE` = '2014' GROUP BY A.ID_COULEUR
SELECT T1.`Couleur`,`CA 2014`, `CA 2015`, `CA 2016`, `CA 2017`
FROM
(SELECT C.NOM_COULEUR AS `Couleur`, SUM(V.`QUANTITE`*V.`PRIX_VENTE`) as `CA 2014` FROM `vendre` AS V INNER JOIN `article` AS A ON A.ID_ARTICLE = V.ID_ARTICLE INNER JOIN `couleur` AS C ON C.ID_COULEUR = A.ID_COULEUR WHERE `ANNEE` = '2014' GROUP BY A.ID_COULEUR ORDER BY C.NOM_COULEUR) AS T1
INNER JOIN
(SELECT C.NOM_COULEUR AS `Couleur`, SUM(V.`QUANTITE`*V.`PRIX_VENTE`) as `CA 2015` FROM `vendre` AS V INNER JOIN `article` AS A ON A.ID_ARTICLE = V.ID_ARTICLE INNER JOIN `couleur` AS C ON C.ID_COULEUR = A.ID_COULEUR WHERE `ANNEE` = '2015' GROUP BY A.ID_COULEUR ORDER BY C.NOM_COULEUR) AS T2
ON T1.Couleur = T2.Couleur
INNER JOIN
(SELECT C.NOM_COULEUR AS `Couleur`, SUM(V.`QUANTITE`*V.`PRIX_VENTE`) as `CA 2016` FROM `vendre` AS V INNER JOIN `article` AS A ON A.ID_ARTICLE = V.ID_ARTICLE INNER JOIN `couleur` AS C ON C.ID_COULEUR = A.ID_COULEUR WHERE `ANNEE` = '2016' GROUP BY A.ID_COULEUR ORDER BY C.NOM_COULEUR) AS T3
ON T1.Couleur = T3.Couleur
INNER JOIN
(SELECT C.NOM_COULEUR AS `Couleur`, SUM(V.`QUANTITE`*V.`PRIX_VENTE`) as `CA 2017` FROM `vendre` AS V INNER JOIN `article` AS A ON A.ID_ARTICLE = V.ID_ARTICLE INNER JOIN `couleur` AS C ON C.ID_COULEUR = A.ID_COULEUR WHERE `ANNEE` = '2017' GROUP BY A.ID_COULEUR ORDER BY C.NOM_COULEUR) AS T4
ON T1.Couleur = T4.Couleur;

SELECT
    C.`nom_couleur` AS Couleur,
    REPLACE(CONCAT(FORMAT(SUM(CASE WHEN V.`ANNEE` = 2014 THEN V.`quantite` * V.`prix_vente` ELSE 0 END),2), ' €'), ',', ' ') AS 'CA 2014',
    REPLACE(CONCAT(FORMAT(SUM(CASE WHEN V.`ANNEE` = 2015 THEN V.`quantite` * V.`prix_vente` ELSE 0 END),2), ' €'), ',', ' ') AS 'CA 2015',
    REPLACE(CONCAT(FORMAT(SUM(CASE WHEN V.`ANNEE` = 2016 THEN V.`quantite` * V.`prix_vente` ELSE 0 END),2), ' €'), ',', ' ') AS 'CA 2016',
    REPLACE(CONCAT(FORMAT(SUM(CASE WHEN V.`ANNEE` = 2017 THEN V.`quantite` * V.`prix_vente` ELSE 0 END),2), ' €'), ',', ' ') AS 'CA 2017'
FROM
    vendre V
INNER JOIN article A ON V.`id_article` = A.`id_article`
INNER JOIN couleur C ON C.`id_couleur` = A.`id_couleur`
WHERE
    V.`ANNEE` BETWEEN 2014 AND 2017
GROUP BY
    C.`nom_couleur`
ORDER BY
    C.`nom_couleur`;


-- vue
CREATE VIEW vue_ca_par_an AS
SELECT
    `ANNEE`,
    SUM(`QUANTITE` * `PRIX_VENTE`) AS 'CA'
FROM
    `vendre`
GROUP BY
    `ANNEE`
ORDER BY
    `ANNEE`;    

  