version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
  php:
    build: .
    volumes:
      - ./:/code

  mysql:
    image: mysql:8.2
    container_name: mysql8
    environment:
      # 🚨 Changer si vous utilisez cette configuration en production
      MYSQL_ROOT_PASSWORD: root_password # ⬅︎ 🚨
      MYSQL_DATABASE: database_name
      MYSQL_USER: root # ⬅︎ 🚨
      MYSQL_PASSWORD: root_password # ⬅︎ 🚨
    ports:
      - "6033:3306" #"6033:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password # ⬅︎ 🚨
    ports:
      - "8081:80"

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025" # smtp
      - "8025:8025" # Boîte mail


volumes:
  mysqldata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './db_server/mysql-phpmyadmin/data'
    